site_name: OPPO A31t Documents
site_description: >-
  A document website for OPPO A31t.
site_author: OPPO A31t Revive Project
repo_url: https://github.com/oppo-a31-revive/Docs
repo_name: oppo-a31-revive/Docs
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 OPPO A31t Revive Project
theme:
  name: material
  language: zh
  font:
    code: false
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.action.copy
    - content.action.select
    - search.suggest
    - search.highlight
    - navigation.tabs
    - header.autohide
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
  palette:
    # Light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    # Dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Light mode

plugins:
  - search
  - git-authors
  - glightbox

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
